### PR TITLE
SONAR-6430 add plugin source revision to JSON response

### PR DESCRIPTION
**Pull request by sns-seb**
information added to response of WS listing installed pluging and pending operations on plugins

### CODE REVIEW

**Comment by simonbrandhof** [comment]
To be consistent with terminology introduced in update center project, "scmRevision" should be renamed to "implementationBuild".
Moreover the JSON example is up-to-date in api/plugins/pending but not in api/plugins/installed.

**Comment by sns-seb** [comment]
> To be consistent with terminology introduced in update center project, "scmRevision" should be renamed to "implementationBuild".

I agree we should be consistent, but "implementationBuild" definitly does not talk to me. I had to look into an existing jar manifest to tell what this field was about and see its value looked a lot like a Git sha1

**Comment by simonbrandhof** [comment]
Yes but in theory this field is not restricted to SCM revision. If we decide to keep "scmRevision", then a ticket should be created in the update center project to keep consistency.

**Comment by sns-seb** [comment]
Lets go with "implementationBuild" to avoid any confusion.

Name is poorly chosen on some aspects but at least it will make clear this JSON field is the same as the one in the manifest in jar files (and since we can not modify the manifest without huge cost, we'll stay with that name)

**Comment by sns-seb** [comment]
PR update:
* rebased on master
* comments taken into account

**Comment by simonbrandhof** [comment]
LGTM

**Pull request merged**
