### PR TITLE
cancelled tasks must no be last

### PR DESCRIPTION
**Pull request by sns-seb**
* fixes SONAR-6925
* also fixed missing index on `Ce_Activity.is_last_key`

### CODE REVIEW

**Comment by julienlancelot** [comment]
It's working as expected, but you didn't implement the solution proposed by @simonbrandhof : instead of updating the way the last executed analysis is find (by update /api/ce/component WS), you've updated the way a ce activity is inserted by keeping the is_last_key to the last "not canceld" analysis.
It's working well but I've no idea of other impact it could have.
@simonbrandhof WDYT ?

**Comment by simonbrandhof** [comment]
@julienlancelot sounds good as the goal is to hide the canceled tasks from current status.

**Comment by julienlancelot** [comment]
@simonbrandhof Ok, thanks !

**Comment by julienlancelot** [comment]
LGTM

**Comment by sns-seb** [comment]
@julienlancelot I had discussed the solution before creating the PR. It also allowed me to find the missing index.

**Pull request merged**
