### PR TITLE
MMF-886 Better first-time developer experience

### PR DESCRIPTION
**Pull request by bartfastiel**
This is a shared feature branch.
:memo::memo::memo::memo::memo::memo::memo::memo::memo::memo::memo::memo:

### CODE REVIEW

**Comment by julienlancelot** [comment]
@bartfastiel I think the based branch is wrong : it's on branch-6.4 but it should be on master, no ?

**Comment by bartfastiel** [comment]
@julienlancelot Absolutely, but I cannot change it currently, because the HEAD of the branch is the HEAD of master. I'll change the base as soon as we have our first commit in this branch.

⚠️  Noone should merge this into the 6.4 branch!

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DefaultWsClient.java#L49](https://github.com/SonarSource/sonarqube/blob/a9648f64f31b01b8d045269c973ec90cdc75c09a/sonar-ws/src/main/java/org/sonarqube/ws/client/DefaultWsClient.java#L49): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1820)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DefaultWsClient.java#L49](https://github.com/SonarSource/sonarqube/blob/2435212bb353fd932c218def0c39e613f5215c94/sonar-ws/src/main/java/org/sonarqube/ws/client/DefaultWsClient.java#L49): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1820)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DefaultWsClient.java#L49](https://github.com/SonarSource/sonarqube/blob/00ea80d91027969ffea6f4ca4ea6dcef068e2731/sonar-ws/src/main/java/org/sonarqube/ws/client/DefaultWsClient.java#L49): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1820)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DefaultWsClient.java#L49](https://github.com/SonarSource/sonarqube/blob/e5720fc52f7a47a382fd4dd5d94c724aecd832cb/sonar-ws/src/main/java/org/sonarqube/ws/client/DefaultWsClient.java#L49): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1820)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DefaultWsClient.java#L49](https://github.com/SonarSource/sonarqube/blob/188e7368764edbb240a6c44e75834afff7ae85a5/sonar-ws/src/main/java/org/sonarqube/ws/client/DefaultWsClient.java#L49): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1820)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
