### PR TITLE
 Refactoring to specialised Functional interfaces 1a78350

### PR DESCRIPTION
**Pull request by ameyaKetkar**

### CODE REVIEW

**Comment by ameyaKetkar** [comment]
Hello,
I am a Graduate Student at Oregon State University, studying the impact of autoboxing. I have written a tool, which analyses the source code to find opportunities to refactor the code to a specialised implementation for primitives, thus eliminating autoboxing. All the changes, have been done manually, and have been verified by me.In this pull request I have specialised two instances of FunctionalInterfaces . I have many more such patches, I will be happy to contribute.

**Comment by simonbrandhof** [comment]
Thanks for the nice contribution. Out of curiosity, did you extend the SonarJava analyzer to implement this rule ?

**Comment by ameyaKetkar** [comment]
Thanks a lot. No I don't use SonarJava, I built an analyser using Eclipse JDT.I would love to discuss(offline) the possibility of using SonarJava as the analyzer. I had tried to use it, but couldn't get a way to obtain filters on binding information. I also have some interesting analysis / refactorings related to maps which I would like to discuss and contribute.

**Comment by simonbrandhof** [comment]
Change applied to master. 
I'm sure that the SonarJava team would enjoy continuing the discussion on https://groups.google.com/forum/#!forum/sonarqube !

**Comment by ameyaKetkar** [comment]
I have made a similar pull request for refactoring Optional to OptionalInt, OptionalDouble, OptionalLong.

**Pull request closed without merging**
