### PR TITLE
Expose `revision` in PostProjectAnalysisTaskTester

### PR DESCRIPTION
**Pull request by codescale**
Hi,

it would be very helpful to have the `revision` property accessible via the PostProjectAnalysisTaskTester.

Thanks :)

### CODE REVIEW

**Comment by pierre-guillot-sonarsource** [comment]
Hi, thanks for your contribution. Could you elaborate a bit about why you would like this `revision` to be accessible? What's the use case behind your request?

**Comment by codescale** [comment]
Sure. I have developed a `PostProjectAnalysisTask` that gets the revision from the given context and uses it to send the analysis result to our SCM system. To be able to test the behavior I'd like to use the `PostProjectAnalysisTaskTester` instead of mocking everything by myself.

**Comment by pierre-guillot-sonarsource** [comment]
> Sure. I have developed a `PostProjectAnalysisTask` that gets the revision from the given context and uses it to send the analysis result to our SCM system. To be able to test the behavior I'd like to use the `PostProjectAnalysisTaskTester` instead of mocking everything by myself.

thanks.

Hey @dbmeneses , any opinion here?

**Review by dbmeneses — APPROVED** [review]

**Comment by dbmeneses** [comment]
Thanks. I'll merge it and it should show up in this repo within 24h.

**Pull request closed without merging**
