### PR TITLE
Stop using deprecated Gradle API

### PR DESCRIPTION
**Pull request by KengoTODA**
Hello 👋 

I [tried to optimize the Gradle build](https://github.com/KengoTODA/sonarqube/issues/1) of SonarQube and found several rooms to improve.
This PR is to suggest replacing deprecated Gradle API with the latest one. Hope that it will help to upgrade Gradle to 7 and 8 in the future. It should give no impact on build performance and built artifacts.

### CODE REVIEW

**Comment by KengoTODA** [comment]
Travis builds failed but I believe it's not related to the change in this PR.

> Cannot find module 'worker_threads'

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @KengoTODA, thank you for your contribution!

Indeed, the build is also broken on `master`, so not related to this PR. We'll fix it ASAP, after which you can rebase on our `master` branch. Once it builds, we'll be able to verify your suggestion 👍 .

**Comment by KengoTODA** [comment]
@wouter-admiraal-sonarsource I've rebased both PRs! Thanks for your help.

**Comment by wouter-admiraal-sonarsource** [comment]
@malena-ebert-sonarsource As this touches the build, can you have a look please 🙏 ?

**Review by malena-ebert-sonarsource — APPROVED** [review]

**Comment by wouter-admiraal-sonarsource** [comment]
Great! @KengoTODA next step is for me to sync your PR with our private repo (this repo is read-only). Your contribution will appear on `master` shortly. I will close this PR now.

Thanks again for your contribution 👍 .

**Pull request closed without merging**
