### PR TITLE
SONAR-6596 Remove database semaphores from batch

### PR DESCRIPTION
**Pull request by julienlancelot**
SONAR-6596 Remove database semaphores from batch

### CODE REVIEW

**Comment by simonbrandhof** [comment]
The class ```org.sonar.core.persistence.SemaphoreUpdater``` must be removed from batch container and annotation @BatchSide removed.

**Comment by simonbrandhof** [comment]
And the class ```org.sonar.core.persistence.SemaphoresImpl```must be removed from batch too.

**Comment by simonbrandhof** [comment]
The number of JDBC connections can be decreased from 3 to 2 on batch. See ```org.sonar.batch.bootstrap.BatchDatabase``` at line 42.

**Comment by julienlancelot** [comment]
@simonbrandhof feedback applied !

**Comment by simonbrandhof** [comment]
LGTM

**Comment by julienlancelot** [comment]
:+1:

**Pull request merged**
