### PR TITLE
Ported fix for ms sqljdbc driver (to use timestamp type) for activere…

### PR DESCRIPTION
**Pull request by demuruge**
…cord-jdbc-adapter. (https://github.com/jruby/activerecord-jdbc-adapter/commit/41c8d8d116844fc8e5057de0ca81bba33b2fa1f4)

### CODE REVIEW

**Comment by sns-seb** [comment]
please rebase your PR on the updated `SonarSource:feature/driver_mssql` branch in order for your PR to be able to successfully build on Travis

:warning: :warning:  pushed force was used on `SonarSource:feature/driver_mssql`  :warning: :warning: 

in addition, please keep the Git commit title to 70 chars or less and use present tense
use a git commit description when details need to be provided

**Comment by sns-seb** [comment]
FYI, build is failing on Travis because of some missing license which is unrelated to your commit

**Comment by demuruge** [comment]
Thanks Sebastien. Should we wait till this issue is fixed? How should we proceed with pushing these changes into feature\driver_mssql & then to master?

**Comment by bellingard** [comment]
@demuruge As Sebastien said, your PR is correct (it has already been green, see https://travis-ci.org/SonarSource/sonarqube/builds/75120162). So this is something that must be handled on our side to get the PR back to green. We'll keep you posted.

**Comment by simonbrandhof** [comment]
PR merged into master. Thanks for the contribution.

**Pull request closed without merging**
