### PR TITLE
Drop project dashboards

### PR DESCRIPTION
**Pull request by stas-vilchik**

### CODE REVIEW

**Comment by simonbrandhof** [comment]
Do we want a safeguard when disabling project dashboards (by keeping the list of them) ? If not, then they should be removed from database (tables DASHBOARDS + ACTIVE_DASHBOARDS + WIDGETS + WIDGET_PROPERTIES) and column DASHBOARDS.IS_GLOBAL should be dropped.

**Comment by stas-vilchik** [comment]
@simonbrandhof surely we want, we have a separate ticket for that (cc @teryk)

**Comment by simonbrandhof** [comment]
The extension point org.sonar.api.web.Dashboard allows plugins to define dashboards. The method `setGlobal()` should be kept for backward-compatibility but documentation should mention that project dashboards are ignored (when `setGlobal(true)` is not called).

**Comment by simonbrandhof** [comment]
The startup task `RegisterDashboards` should filter project dashboards.

**Pull request merged**
