### PR TITLE
fix minor typo in comment in sonar.properties

### PR DESCRIPTION
**Pull request by sns-seb**
this fixes a minor typo in a sonar.properties comment
this also serves as a test for the PR process and GitHub setup

### CODE REVIEW

**Comment by julienlancelot** [comment]
Good catch Sebastien !
One small feedback, we're using the following naming convention for the name of the branch : feature/XXX, where XXX is a small description of the feature.

Anyway, LGTM

**Comment by sns-seb** [comment]
@julienlancelot should I recreate the PR with the right name then ?

**Comment by julienlancelot** [comment]
@sns-seb No, it was just a remark for next time.

**Comment by sns-seb** [comment]
not merged, comment change already pushed to master by @simonbrandhof as part of another commit

**Comment by simonbrandhof** [comment]
@sns-seb sorry I didn't see your PR !

**Pull request closed without merging**
