### PR TITLE
SONAR-7364 remove SQALE characteristics

### PR DESCRIPTION
**Pull request by simonbrandhof**

### CODE REVIEW

**Comment by simonbrandhof** [comment]
Remaining stuff:
- deprecate characteristics in RulesDefinition API
- remove columns in RULES and PROJECT_MEASURES

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 4 minor
* INFO 8 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L594) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* MAJOR [Add the missing @Deprecated annotation.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L594) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
* MINOR [Remove this unused import 'org.sonar.api.server.debt.internal.DefaultDebtCharacteristic'.](https://github.com/SonarSource/sonarqube/blob/4f694ec936f0847156f7d23ff132a23f4d65e09b/server/sonar-server/src/main/java/org/sonar/server/issue/ws/ShowAction.java#L34) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AUselessImportCheck)
* ... 5 more

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 1 minor
* INFO 11 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L595) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L155) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/6b50d148ee40a937fe0bcc5001b209f41cfbd1ba/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L771) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* ... 5 more

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 1 minor
* INFO 11 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L595) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L155) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/464828de493df649558299de6f1c4203cfda7062/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L771) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* ... 5 more

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 1 minor
* INFO 11 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L595) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L155) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L771) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* ... 5 more

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 1 minor
* INFO 11 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L595) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L155) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/06e669fb02f97021c216940da06c0e32da5f6257/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L771) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* ... 5 more

**Comment by SonarTech** [comment]
SonarQube analysis reported 15 issues:
* MAJOR 3 major
* MINOR 1 minor
* INFO 11 info

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L529) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L538) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L548) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L557) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L567) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L576) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L586) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/rules/Rule.java#L595) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L155) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* INFO [Do not forget to remove this deprecated code someday.](https://github.com/SonarSource/sonarqube/blob/ba954543c30eeaaf2031beedfcec245cf47e3822/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L771) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1133)
* ... 5 more

**Pull request closed without merging**
