### PR TITLE
Upgrade Apache Commons Collections to v3.2.2

### PR DESCRIPTION
**Pull request by jart**
Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!

https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

### CODE REVIEW

**Comment by simonbrandhof** [comment]
Thanks for the contribution, PR applied. Note that it resurrects the old wish to drop usage of commons-collections. It will probably be done for next version.

**Comment by jart** [comment]
Out of curiosity, are you switching to Guava?

**Comment by simonbrandhof** [comment]
Yes.

**Comment by simonbrandhof** [comment]
Note that commons-collections will still be available in classpath of plugins built with API < 5.2 to not break backward-compatibility.

**Comment by jart** [comment]
I'm glad you're using Guava :+1: 

If Commons Collections v3.2.1 is still on the classpath, then you're still vulnerable. I strongly recommend updating to v3.2.2 by merging this PR. The only behavior change in the new version is to disable the deserialization of unsafe classes in the functor package.

**Comment by simonbrandhof** [comment]
As I said, your PR is already applied, see https://github.com/SonarSource/sonarqube/commits/master :-)

**Comment by jart** [comment]
Oh you're awesome. Thank you for helping keep the open source community safe.

**Pull request closed without merging**
