### PR TITLE
SONAR-6478 WS permissions/search_global_permissions search for global permissions

### PR DESCRIPTION
**Pull request by teryk**

### CODE REVIEW

**Comment by sns-seb** [comment]
@teryk back to you

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 2 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'src/main/java/org/sonar/db/permission' package (org.codehaus.sonar:sonar-db:src/main/java/org/sonar/db/permission) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1228)
* MAJOR Add a 'package-info.java' file to document the 'src/main/java/org/sonar/server/permission/ws' package (org.codehaus.sonar:sonar-server:src/main/java/org/sonar/server/permission/ws) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1228)

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 issues:
* MAJOR 2 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'src/main/java/org/sonar/db/permission' package (org.codehaus.sonar:sonar-db:src/main/java/org/sonar/db/permission) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1228)
* MAJOR Add a 'package-info.java' file to document the 'src/main/java/org/sonar/server/permission/ws' package (org.codehaus.sonar:sonar-server:src/main/java/org/sonar/server/permission/ws) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1228)

**Comment by teryk** [comment]
LGTH @sns-seb

**Pull request closed without merging**
