### PR TITLE
SONAR-5968 Allow modification of issue filter using issue properties

### PR DESCRIPTION
**Pull request by stas-vilchik**

### CODE REVIEW

**Comment by jblievremont** [comment]
LGTM, and it gave me a good insight on how new icons/glyphs are added to the internal font :)

**Comment by simonbrandhof** [comment]
* filter dropdown must be always available. Currently it's restricted to issue permalink (filter on issue key)
* rule item must be moved to the second section (with tags)
* filter on issue key can not be unselected in sidebar

**Comment by simonbrandhof** [comment]
Btw, I forgot to mention: it rocks.

**Comment by stas-vilchik** [comment]
@simonbrandhof I don't have the issue 
> Currently it's restricted to issue permalink

Can you check again?

**Comment by simonbrandhof** [comment]
Fixed. LGTM too !

**Pull request merged**
