### PR TITLE
Client authentication with certificate

### PR DESCRIPTION
**Pull request by cdroescher**
I would like to be able to authenticate with a client certificate. If a certificate will be provided, a login should be performed automatically and no login prompt should be shown. If there is no certificate, a basic authentication login should be performed.

### CODE REVIEW

**Comment by simonbrandhof** [comment]
JIRA ticket is https://jira.codehaus.org/browse/SONAR-5639

**Comment by chkpnt** [comment]
Since _["native SSL support is no longer supported"](http://docs.sonarqube.org/display/SONAR/Release+5.4+Upgrade+Notes)_, I guess this issue shouldn't be longer tagged as planned.

**Comment by charlesfendt** [comment]
No need of a native SSL support to allow client certificate authentication...
All you need is a reverse proxy wich set (and reset) the standard HTTP headers:
SSL_CLIENT_S_DN (the client subject DN)
SSL_CLIENT_I_DN (the client issuer DN)
...

We need an authentication plugin based on HTTP request header
- which header (E.g. SSL_CLIENT_S_DN)
- how to extract log based on a regexp (E.g. .* email = ([^,]*), .* )

**Comment by simonbrandhof** [comment]
I'm closing this PR as it can't be applied as-this. The Ruby on Rails authentication layer has been dropped in 6.x series. 
The feature is tracked in https://jira.sonarsource.com/browse/SONAR-5639.
Thanks.

**Pull request closed without merging**
