### PR TITLE
SONAR-6537 Add HTTP security headers

### PR DESCRIPTION
**Pull request by simonbrandhof**
See https://jira.codehaus.org/browse/SONAR-6537

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by jblievremont** [comment]
It's strange, although I can see the headers added to the response object, they are not written to the response stream. Still digging to understand this behavior.

**Comment by simonbrandhof** [comment]
The reason is that Rack probably resets headers.

**Comment by SonarTech** [comment]
SonarQube analysis reported no new issues.

**Comment by simonbrandhof** [comment]
It works well except for static resources like images. I wonder if it can be a vulnerability for mime-sniffing.
Anyway LGTM

**Pull request closed without merging**
