### PR TITLE
Add config parameter to increase elasticsearch index.max_result_window

### PR DESCRIPTION
**Pull request by tuomari**
When fetching over 10000 issues through api ( /api/issues/search?p=21&ps=-1 ), elasticsearch fails with exception `Result window is too large, from + size must be less than or equal to: [10000] but was [10500].` Increasing `index.max_result_window` will allow fetching of all issues for a project. 

For example IntelliJ Idea sonarqube plugin (https://github.com/sonar-intellij-plugin/sonar-intellij-plugin) will fail if there are over 10000 issues in a project..

### CODE REVIEW

**Comment by sns-seb** [comment]
Hello,

Increasing `index.max_result_window` is not fixing the problem, only pushing it a bit further away, at the cost of memory (see `index.max_result_window` at https://www.elastic.co/guide/en/elasticsearch/reference/6.8/index-modules.html#dynamic-index-settings) and bad performance.

WS api/issues/search should rather be fixed to use ES's scroll API.

Anyway, it's questionable whether it makes sense to display more than 10k issues per project at all without putting in any extra filter (issue type at least), and even more in an IDE.

**Comment by inoreip** [comment]
Hi

Can we at least make sonarqube honour any settings in the elasticsearch.yml file on startup. It seems strange you cannot tailor the search index behaviour to a particular deployment. Even if these properties are defined in SonarQube.properties file.

**Comment by vanderby** [comment]
While this PR does make this ES setting a first class citizen, it is not needed. If you enable ES's http port by setting sonar.search.httpPort you can then make a PUT request to change any ES setting. A more detailed walkthrough can be found at: https://github.com/vanderby/SonarQube-AzureAppService/issues/40#issuecomment-624414812

Depending on how your setup with SQ is, you may want to disable the ES http port after the change so you don't keep the endpoint open to the public internet.

**Comment by pierre-guillot-sonarsource** [comment]
Hey @jacek-poreda-sonarsource, could you handle this one, please?

**Comment by jacek-poreda-sonarsource** [comment]
Hello @tuomari ,

Thanks for the contribution, but as @sns-seb mentioned, it is not fixing root of the problem, just postponing it further.

Also with the current state of Elasticsearch API I'm unsure if scroll api should be used here either, hence I'm closing that PR.

**Pull request closed without merging**
