### PR TITLE
SONAR-6379 add Java WS to list plugin updates

### PR DESCRIPTION
**Pull request by sns-seb**
This PR:

* adds a new WS to list installed plugins for which a newer version is available
* adds explicit sorting of plugins in response of available WS (done in this PR because code is common with updatable WS)

### CODE REVIEW

**Comment by simonbrandhof** [comment]
@sns-seb as written in the description, multiple versions of the same plugin can be returned. How this case is handled by the JSON response ? Multiple "plugins" with same key ?

**Comment by sns-seb** [comment]
I double-checked the `UpdateCenter` code, only one version is returned per plugin (the latest compatible with the current version of SQ). The description is inaccurate and I shall try and find a new and non ambiguous way to write it.

**Comment by simonbrandhof** [comment]
That's strange. That means that it's not possible to see the changelog of all the versions greater than the installed one.

**Comment by sns-seb** [comment]
Well, triple-checking wasn't a waste. I read the install part of the update center code.

currently, each plugin version will be displayed as a separate plugin object in the list. I don't think this appropriate but that's how UpdateCenter provides the information.

**Comment by simonbrandhof** [comment]
I know we should think about future changes, but in this specific case shouldn't we prepare the JSON response with an appropriate format ?

**Comment by sns-seb** [comment]
PR updated : 

* rebased on master
* URL renamed to /api/plugins/updates

**Comment by simonbrandhof** [comment]
LGTM

**Pull request merged**
