### PR TITLE
add AuthorDao.selectAll

### PR DESCRIPTION
**Pull request by sns-seb**
added for Developer Cockpit to implement a much faster `DeveloperRepository`

### CODE REVIEW

**Comment by julienlancelot** [comment]
Isn't it dangerous to all all developer in memory ? Wouldn't it be possible to do some streaming ?

**Comment by sns-seb** [comment]
we are loading rows of table AUTHORS. I don't think that will represent a lot of rows

**Comment by julienlancelot** [comment]
The number of authors is the number of commiters, it can be up to something to 100.000 maybe

**Comment by sns-seb** [comment]
looking at how the result of `selectAll` is used, I don't see any benefits from streaming data from table AUTHORS. We want all the perso ids to that we can then read table PROJECTS with the least possible queries.

**Comment by julienlancelot** [comment]
So why not stream and only keep in memory what you need ?

**Comment by sns-seb** [comment]
I need 2 fields out or 5 from `AuthorDto`.
So, I'll need to create another type to hold these 2 fields and add code complexity to use a `ResultHandler`
I'm really not sure of the maintenance and memory benefit

**Comment by SonarTech** [comment]
SonarQube analysis reported 1 issue:
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR Add a 'package-info.java' file to document the 'protobuf' package (org.sonarsource.sonarqube:sonar-db:target/generated-sources/protobuf/org/sonar/db/protobuf) [rule](https://dory.sonarsource.com/coding_rules#rule_key=squid%3AS1228)

**Comment by julienlancelot** [comment]
@sns-seb Let's talk about it with @simonbrandhof

**Comment by sns-seb** [comment]
changes introduced by this PR dropped, closing

**Pull request closed without merging**
