### PR TITLE
SONAR-6368 Remove deprecated violation API

### PR DESCRIPTION
**Pull request by henryju**

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 8 issues:
* CRITICAL 7 critical
* MAJOR 1 major

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* MAJOR [Remove this unused "moduleIssues" private field.](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-batch/src/main/java/org/sonar/batch/index/DefaultIndex.java#L94) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AS1068)
* CRITICAL [Method 'public org.sonar.api.batch.Event createEvent(java.lang.String, java.lang.String, java.lang.String, java.util.Date)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void saveLink(org.sonar.api.resources.ProjectLink)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Collection getIncomingDependencies(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.List getEvents(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void setSource(org.sonar.api.resources.Resource, java.lang.String)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void addViolation(org.sonar.api.rules.Violation)' has been removed](https://github.com/SonarSource/sonarqube/blob/293cb0d3878270c1ea8c52dc29fb0bd9e2cecd9f/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Comment by simonbrandhof** [comment]
Note that this PR must be merged when Decorator extensions are fully disabled.

**Comment by henryju** [comment]
Few plugins are still using the deprecated Violation API: At least c, cpp and web.

**Comment by simonbrandhof** [comment]
LGTM

**Comment by SonarTech** [comment]
SonarQube analysis reported 7 issues:
* CRITICAL 7 critical

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* CRITICAL [Method 'public java.util.List getViolations(org.sonar.api.violations.ViolationQuery)' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public org.sonar.api.batch.DecoratorContext saveViolation(org.sonar.api.rules.Violation)' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void deleteLink(java.lang.String)' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void saveLink(org.sonar.api.resources.ProjectLink)' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.List getEvents(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Removed org.sonar.graph.DirectedGraphAccessor from the set of implemented interfaces](https://github.com/SonarSource/sonarqube/blob/5e58d10a267799b5f73e701ab52e38b87a205a88/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Comment by SonarTech** [comment]
SonarQube analysis reported 7 issues:
* CRITICAL 7 critical

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* CRITICAL [Method 'public org.sonar.api.batch.Event createEvent(java.lang.String, java.lang.String, java.lang.String, java.util.Date)' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.List getViolations()' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Collection getIncomingDependencies(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void deleteEvent(org.sonar.api.batch.Event)' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void setSource(org.sonar.api.resources.Resource, java.lang.String)' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.List getEvents(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/7ce9f4c01efa7938653367baf845ebbd23be9acd/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Comment by SonarTech** [comment]
SonarQube analysis reported 7 issues:
* CRITICAL 7 critical

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* CRITICAL [Method 'public void deleteEvent(org.sonar.api.batch.Event)' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Collection getOutgoingDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void saveLink(org.sonar.api.resources.ProjectLink)' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Collection getIncomingDependencies(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Removed org.sonar.graph.DirectedGraphAccessor from the set of implemented interfaces](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/542e838f4dfa1f90a6517874471f785953b13ed4/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Comment by SonarTech** [comment]
SonarQube analysis reported 7 issues:
* CRITICAL 7 critical

Watch the comments in this conversation to review them.
Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
* CRITICAL [Method 'public org.sonar.api.batch.DecoratorContext saveViolation(org.sonar.api.rules.Violation, boolean)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.Set getDependencies()' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/DecoratorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public java.util.List getEvents(org.sonar.api.resources.Resource)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void saveViolation(org.sonar.api.rules.Violation, boolean)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void saveViolations(java.util.Collection)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SensorContext.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void addViolation(org.sonar.api.rules.Violation, boolean)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* CRITICAL [Method 'public void deleteEvent(org.sonar.api.batch.Event)' has been removed](https://github.com/SonarSource/sonarqube/blob/232ae7083e7e9fc83e9e171d7174944fae26fcb3/sonar-plugin-api/src/main/java/org/sonar/api/batch/SonarIndex.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Pull request merged**
