### PR TITLE
SQCOM-7 Add a custom footer for sonarqube.com

### PR DESCRIPTION
**Pull request by gregaubert**

### CODE REVIEW

**Comment by gregaubert** [comment]
Ok I'll add them

**Comment by gregaubert** [comment]
I just have a doubt about branding message @stas-vilchik. I can't find the current branding message of SQ.com : "SonarQube™ technology is powered by SonarSource SA" in the code base.
How is it done ? Will it really work with what I've done in the PR ?

**Comment by stas-vilchik** [comment]
Good question :) When SonarQube is been building for production, the release profile is used. It's done like `./build.sh -Prelease`. When this profile is used, some [files from SonarSource/sonarsource-branding](https://github.com/SonarSource/sonarsource-branding/blob/master/src/main/webapp/src/main/js/app/components/GlobalFooterBranding.js) is copied to overwrite some others. This is how you get the branding footer.

**Comment by gregaubert** [comment]
Oh ok! So I should change what I did and update the sonarsource-branding project instead...

**Comment by gregaubert** [comment]
@stas-vilchik You can review just last commit, then I'll squash them together when merging.

**Pull request closed without merging**
