### PR TITLE
Expose security standards from rule webservice API

### PR DESCRIPTION
**Pull request by noahbkim**
For a project I am working on I need to be able to access the CWE associated with each issue on a project. As far as I can tell, this information is not externally available. I figured the most intuitive place to make this available from would be the rule model, as security standards are attached to rules internally. I am unsure of how to write a unit test for this endpoint, but can do so if needed!

### CODE REVIEW

**Comment by noahbkim** [comment]
Not sure why the Travis CI build failed, doesn't seem to be related to the actual code 😢

**Comment by farnulfo** [comment]
Hi, just to let you know, there is some issue with Travis, they're working on it :
https://twitter.com/farnulfo/status/1134114199997702145
https://github.com/SonarSource/sonarqube/pull/3211#issuecomment-497657033

**Comment by noahbkim** [comment]
Is there any way to rerun the checks without pushing an empty commit?

**Comment by farnulfo** [comment]
Hi @noahbkim , my PR https://github.com/SonarSource/sonarqube/pull/3211 is now fine.
You can close your PR and then Reopen it. It will relaunch the Continuous Integration.

**Comment by pierre-guillot-sonarsource** [comment]
@julienlancelot can you have a look at this please ? :)

**Comment by noahbkim** [comment]
Hey guys, I'm no longer involved in the project that required this feature. I also don't have the build set up on any of my machines, so I will not be contributing to this PR. However, in the case you guys/someone else wants to see it through, I'll leave it open?

**Comment by julienlancelot** [comment]
Thanks for your contribution @noahbkim. I'm closing it as for the moment this feature is not needed.

**Pull request closed without merging**
