### PR TITLE
Refactoring for specialising Optional

### PR DESCRIPTION
**Pull request by ameyaKetkar**
Hello,
Like the specialisation of Functional interfaces in the previous pull request, these are the results I obtained while testing specialisation of java.util.Optional.
There have been a few autoboxings introduced by the refactorings, but they are in the test files. That was the price to pay from eliminating autoboxing from prod files.

### CODE REVIEW

**Comment by sns-seb** [comment]
Hello @ameyaKetkar ,

What was the scope of the analysis you ran? (my understanding is you used a tool)

I'm surprised the PR does not include fixes for https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/config/Configuration.java#L136 or https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/config/Configuration.java#L149, for example.

**Comment by ameyaKetkar** [comment]
Hello,
Yes, those changes are pending along with MigrationHistory.java and DatabaseVersion.java. The reason I didn't check in earlier is because the refactorings required are a bit too complex for the current state of my tool :( . Especially the ones in ConfigurationTest.java and PurgeConfiguration.java. I have made those changes manually for now and committed them to my branch. 
Thank you for your interest.

**Comment by ameyaKetkar** [comment]
Hello,
Yes, those changes are pending along with MigrationHistory.java and databaseVersion.java. The reason I didn't check in them earlier is because the refactorings required are a bit too complex for the current state of my tool. Especially the ones in ConfigurationTest.java and PurgeConfiguration.java. I have made those changes manually for now and committed them to my branch. 
Thank you.

**Comment by ameyaKetkar** [comment]
My apologies. After adding the new changes, the build fails because there is an exception which i am unable to understand. I can just close this PR for now.

**Comment by ameyaKetkar** [comment]
Hello @sns-seb ,
I have created another pull request for refactoring. 
https://github.com/SonarSource/sonarqube/pull/2838
(getDouble() in Configuration.java is not refactored since it has no calls with are autoboxed.)
Thank you.

**Pull request closed without merging**
