### PR TITLE
Do not break if navigator.language == undefined

### PR DESCRIPTION
**Pull request by t-8ch**
(Note this is actually not tested, so I don't know whether it fixes the issue completely)

Related to #1151

### CODE REVIEW

**Comment by julienlancelot** [comment]
@t-8ch Im not sure to understand, what is this PR about ?

**Comment by t-8ch** [comment]
@julienlancelot this makes SonarQube usable in browsers that do not have an explicit language choice configured.

**Comment by t-8ch** [comment]
Otherwise the login process will not finish but die with an Javascript exception and show the spinner forever.

**Comment by t-8ch** [comment]
In Firefox you can go to about:preferences#content , click the "Languages" button and remove all configured languages.
Then try to log into sonarcloud.io

**Comment by stas-vilchik** [comment]
thanks for the contribution @t-8ch !

**Pull request merged**
