### PR TITLE
SONAR-6637 Stop filling db column PROJECT_MEASURES.RULE_PRIORITY

### PR DESCRIPTION
**Pull request by simonbrandhof**
SONAR-6637 Stop filling db column PROJECT_MEASURES.RULE_PRIORITY

### CODE REVIEW

**Comment by SonarTech** [comment]
SonarQube analysis reported 7 new issues:
* 2 critical
* 5 minor

Details:
* [Remove this unused import 'org.sonar.batch.protocol.Constants'.](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-batch/src/main/java/org/sonar/batch/report/MeasuresPublisher.java#L36) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* [Remove this unused import 'org.sonar.api.rules.RulePriority'.](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-batch/src/main/java/org/sonar/batch/report/MeasuresPublisher.java#L32) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* [Remove this unused import 'javax.persistence.EnumType'.](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java#L32) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* [Remove this unused import 'org.sonar.api.rules.RulePriority'.](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java#L27) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* [Method 'public org.sonar.api.database.model.MeasureModel setMeasureDate(java.util.Date)' has been removed](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* [Remove this unused import 'javax.persistence.Enumerated'.](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java#L33) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=squid%3AUselessImportCheck)
* [Method 'public java.util.Date getMeasureDate()' has been removed](https://github.com/SonarSource/sonarqube/blob/988f518f5555acf5458daf7d1a655909fd46d6fd/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Comment by julienlancelot** [comment]
@seb In fact the severity was just a kind of metadata associated on rules measures. If the rule_id, the rule_priority (severity) is also null. 
It means that these checks could have already been removed a long time again. Probably that in the past, some measures had some severities without having some rules, but it's no more the case anymore.
So removing these checks seems ok for me.

**Comment by julienlancelot** [comment]
LGTM

**Comment by SonarTech** [comment]
SonarQube analysis reported 2 new issues:
* 2 critical

Details:
* [Method 'public org.sonar.api.database.model.MeasureModel setMeasureDate(java.util.Date)' has been removed](https://github.com/SonarSource/sonarqube/blob/e72764422fd7fca3c1a04e5e89d16105b043df12/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)
* [Method 'public org.sonar.api.rules.RulePriority getRulePriority()' has been removed](https://github.com/SonarSource/sonarqube/blob/e72764422fd7fca3c1a04e5e89d16105b043df12/sonar-plugin-api/src/main/java/org/sonar/api/database/model/MeasureModel.java) [rule](http://nemo.sonarqube.org/coding_rules#rule_key=clirr%3Aclirr-api-break)

**Pull request closed without merging**
