### PR TITLE
Various XSS fixes (2)

### PR DESCRIPTION
**Pull request by ustramooner**
some more XSS fixes - now for when user is logged in

### CODE REVIEW

**Comment by jblievremont** [comment]
Hi, thank you for your contribution!

It should get merged in 4.5.5 LTS as well as in current master (5.2).

**Comment by simonbrandhof** [comment]
@ustramooner about the 2nd commit (CSRF vulnerability), do you know how it can be reproduced ?

**Comment by ustramooner** [comment]
i used ZAP (https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project) to reproduce all these issues.

**Comment by ustramooner** [comment]
@stas-vilchik any reason this is not being merged?

**Comment by stas-vilchik** [comment]
@ustramooner we're not going to do another LTS (4.5.7) release, and the issue with permissions doesn't exist in the latest releases.

**Pull request closed without merging**
