### PR TITLE
SONAR-7959 Remove ppc64 arch from wrapper

### PR DESCRIPTION
**Pull request by simonbrandhof**
https://jira.sonarsource.com/browse/SONAR-7959

### CODE REVIEW

**Comment by Godin** [comment]
@simonbrandhof you forgot
```
$ file sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib
sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib: Mach-O universal binary with 2 architectures
sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib (for architecture ppc64):	Mach-O 64-bit bundle ppc64
sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib (for architecture x86_64):	Mach-O 64-bit bundle x86_64

$ lipo sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib -extract_family x86_64 -output sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib
```

**Comment by simonbrandhof** [comment]
Good catch, it's fixed.

**Comment by Godin** [comment]
While in general I don't like presence of binaries in source code repositories, this change does what should:
```
$ lipo -info sonar-application/src/main/assembly/bin/macosx-universal-64/wrapper
Non-fat file: sonar-application/src/main/assembly/bin/macosx-universal-64/wrapper is architecture: x86_64

$ lipo -info sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib
Non-fat file: sonar-application/src/main/assembly/bin/macosx-universal-64/lib/libwrapper.jnilib is architecture: x86_64
```

**Comment by simonbrandhof** [comment]
I agree, copying binaries in project is crap. Still creating a project for JSW is a pain too.

**Pull request closed without merging**
