### PR TITLE
Rewrite new coverage steps into a single one, using Formula

### PR DESCRIPTION
**Pull request by sns-seb**
My initial intent was to merge both New Coverage steps into `CoverageMeasureStep` but, code-wise, new coverage formulas are too much unrelated to formula of `CoverageMeasureStep` so I kept it separated

### CODE REVIEW

**Comment by julienlancelot** [comment]
I think it's too early to finish the review as you haven't finished yet (I see that "WIP merging new coverage computation into CoverateMeasuresStep" contains unfinished code)

**Comment by sns-seb** [comment]
I've forgotten to rebase my branch, hang on a sec

**Comment by julienlancelot** [comment]
Ok, ping me when it's ok

**Comment by julienlancelot** [comment]
Ok, ping me when it's ok

**Comment by sns-seb** [comment]
@julienlancelot back to you

**Comment by julienlancelot** [comment]
LGTM !

**Pull request merged**
