### PR TITLE
Fix warning message when minimal version of required plugin is not installed

### PR DESCRIPTION
**Pull request by gquerret**
There was a problem with the order of the parameters, and an invalid character was present in the string.

### CODE REVIEW

**Comment by pierre-guillot-sonarsource** [comment]
Hey @jacek-poreda-sonarsource could you have a look at this, please? :)

**Comment by jacek-poreda-sonarsource** [comment]
Hey, 

First of all thanks for your contribution!

Change looks good, but could you also add a test to verify logs in this test class method:

```java
ServerPluginRepositoryTest#plugin_is_ignored_if_required_plugin_is_too_old_at_startup
```

**Comment by gquerret** [comment]
Test added + squashed & rebased commits

**Comment by jacek-poreda-sonarsource** [comment]
Thanks for contribution once again! Your commit has been synced to this repo.

**Pull request closed without merging**
