### PR TITLE
Removing unused imports

### PR DESCRIPTION
**Pull request by artsmandev**
My suggests are on `cosmetic changes` and `typo fixes`:

1. I found unused imports on these classes.

- [x]  Use the following formatting style: SonarSource/sonar-developer-toolset
- [x] Provide a unit test for any code you changed
- [ ] If there is a JIRA ticket available, please make your commits and pull request start with the ticket ID (SONAR-XXXX)

Thank you.

### CODE REVIEW

**Comment by jacek-poreda-sonarsource** [comment]
Hey, thanks, though there are more unused import to be removed:

```
* ServerImpl.java
* BuiltInQProfileInsertImpl.java
* SearchAction.java
* SetTypeAction.java
* BulkApplyTemplateAction.java
* AesCipher.java
* Server.java
* DefaultServer.java
```

Could you take care of them as well?

**Comment by artsmandev** [comment]
> Hey, thanks for the contribution, though there are more unused import to be removed:
> 
> ```
> * ServerImpl.java
> * BuiltInQProfileInsertImpl.java
> * SearchAction.java
> * SetTypeAction.java
> * BulkApplyTemplateAction.java
> * AesCipher.java
> * Server.java
> * DefaultServer.java
> ```
> 
> Could you take care of them as well?

Oh, that's cool, @jacek-poreda-sonarsource !
I will take take of them, too.
I'm happy to help, (=

from smartphone.

**Comment by jacek-poreda-sonarsource** [comment]
Thanks for fixing those issues. Could you also squash commits with a message in present imperative tense? For instance: `Code smell fix: Remove unused imports`

**Comment by artsmandev** [comment]
> Thanks for fixing those issues. Could you also squash commits with a message in present imperative tense? For instance: `Code smell fix: Remove unused imports`

Done. (=

**Comment by jacek-poreda-sonarsource** [comment]
Thanks again for contribution, it should be sync to this repo soon.

**Pull request closed without merging**
