### PR TITLE
Display About page faster

### PR DESCRIPTION
**Pull request by gregaubert**
Related to https://groups.google.com/a/sonarsource.com/d/topic/dogfood-sonarqube/KST_kILd_Uc/discussion

### CODE REVIEW

**Comment by gregaubert** [comment]
:+1: It does look better with only one spinner each.
I added the global loading spinner in the index page too. I had to move the style to a less file to have it available there.

There is an "issue" though, the global loading blink when the js files are loaded.

**Comment by gregaubert** [comment]
Ok, with this the blink is a little less noticeable but we can still see it

**Comment by gregaubert** [comment]
@stas-vilchik Do you think there is something else we could do to remove or reduce the blink ?

**Comment by stas-vilchik** [comment]
@gregaubert I think it's fine now.

**Comment by gregaubert** [comment]
Ok I'll merge then

**Pull request merged**
