### PR TITLE
Add Gitea ALM integration

### PR DESCRIPTION
**Pull request by lafriks**
Add support for Gitea (https://gitea.io/) ALM integration.

Any feedback would be nice.

### CODE REVIEW

**Comment by pierre-guillot-sonarsource** [comment]
Hi, thanks for your contribution. I see that you were inspired by the GitHub integration, could you please specify in what extends they are similar? I'm not familiar at all with Gitea.

Also, the PR decoration mechanism is close-source, so accepting this PR as-is would only result in creating some endpoint, but the actual PR decoration mechanism would not be implemented.

**Comment by lafriks** [comment]
@pierre-guillot-sonarsource yes, Gitea has very similar API to GitHub rest API (endpoints/json structure etc). I was looking as possibility to implement this as plugin but there is no way to extend this through plugins. If there was ALM integration definition in SonarQube core. Decorations would be possible to implement using plugin as otherwise there is currently no other way I could find as even ClientDb can not be extended to add this. Especially ALM enum is limiting factor for this.

**Comment by pierre-guillot-sonarsource** [comment]
Currently, is there is something stopping you to create a GitHub integration, and define as API endpoint your Gitea url?

**Comment by lafriks** [comment]
They are not really exact. For example GitHub organizations would be: `GET https://api.github.com/users/lafriks/orgs` vs `GET https://<gitea-host>/api/v1/users/lafriks/orgs` and there are quite some more small differences so they will not work out of the box anyway.

**Comment by lafriks** [comment]
@pierre-guillot-sonarsource I could most probably implement decorations myself for Gitea as plugin if #3249 got merged as currently than enum is blocking any way to extend this through plugins.

**Comment by pierre-guillot-sonarsource** [comment]
Hi, thanks for your suggestion. Unfortunately adding Gitea to the list of supported ALM would require much more work than that (including the web UI). Your best option to make this happen is to push as a feature request on our [community forum](https://community.sonarsource.com/)

**Comment by tomroffe** [comment]
As a paying customer... I would very much like to use an ALM intergration for gitea.

**Pull request closed without merging**
