### PR TITLE
SONAR-10215 dont fail in migration 1642 when perm template is missing

### PR DESCRIPTION
**Pull request by sns-seb**
by not blindling copy the value of property storing the view permission template UUID to the organization table in DB migration 1509

### CODE REVIEW

**Comment by simonbrandhof** [comment]
@sns-seb the following error is raised locally when upgrading from 6.3 with an invalid value in {{organizations.default_perm_template_view}}:

```
2018.01.11 16:03:57 ERROR web[][o.s.s.p.d.m.DatabaseMigrationImpl] DB migration ended with an exception
org.sonar.server.platform.db.migration.step.MigrationStepExecutionException: Execution of migration step #1642 'Support private project in default permission template' failed
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:79)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:67)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:590)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:52)
        at org.sonar.server.platform.db.migration.engine.MigrationEngineImpl.execute(MigrationEngineImpl.java:50)
        at org.sonar.server.platform.db.migration.DatabaseMigrationImpl.doUpgradeDb(DatabaseMigrationImpl.java:105)
        at org.sonar.server.platform.db.migration.DatabaseMigrationImpl.doDatabaseMigration(DatabaseMigrationImpl.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Permission template with uuid adadad not found
        at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
        at org.sonar.server.platform.db.migration.version.v64.SupportPrivateProjectInDefaultPermissionTemplate.getPermTemplateId(SupportPrivateProjectInDefaultPermissionTemplate.java:115)
        at org.sonar.server.platform.db.migration.version.v64.SupportPrivateProjectInDefaultPermissionTemplate.readOrganizationProperties(SupportPrivateProjectInDefaultPermissionTemplate.java:104)
        at org.sonar.server.platform.db.migration.version.v64.SupportPrivateProjectInDefaultPermissionTemplate.execute(SupportPrivateProjectInDefaultPermissionTemplate.java:50)
        at org.sonar.server.platform.db.migration.step.DataChange.execute(DataChange.java:39)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:75)
        ... 11 common frames omitted

```

**Comment by simonbrandhof** [comment]
Is the first commit 742482b38c06e350f1e87866299f01497cfe229a still required ? Fixing output of migration 1509 in 6.3 seems to be useless because migration 1642 in 6.4 cleans-up input. Am I correct ?

**Comment by simonbrandhof** [comment]
Successfully tested from 6.2 and 6.3.1.

**Comment by sns-seb** [comment]
> Is the first commit 742482b still required ? Fixing output of migration 1509 in 6.3 seems to be useless because migration 1642 in 6.4 cleans-up input. Am I correct ?

It can be removed since both migrations are executed anyway (and even though dropping code is a bit of a pain)

**Comment by sns-seb** [comment]
I've removed the first commit and tried again migration from 5.6.7, 6.2, 6.3.1 and 6.4. It works.

**Pull request closed without merging**
