### PR TITLE
SONAR-6867: Add a new APIs UserDetails.getUserId()/setUserId(userId)

### PR DESCRIPTION
**Pull request by sulabh-msft**
SONAR-6867: Add a new APIs UserDetails.getUserId()/setUserId(String userId)
 to allow plugins to pass userId information to SonarQube
setUserId(String userId) and getUserId () are added to UserDetails.

Testing
 1. Unit test for UserDetails
 2. Verification of following scenarios :
    a. Plugin (e.g. LDAP) is dependent on older sonarqube plugins apis
       ( < 5.2) and the plugin is being used in SonarQube 5.2 server
    b. Plugin is dependent on SonarQube 5.2 plugin apis and userId is not
       being populated in UserDetails along with userName and Email .
    c. Plugin is dependent on SonarQube 5.2 plugin apis and userId is
       also being populated by the plugin in UserDetails along with
       userName and Email.

### CODE REVIEW

**Comment by sns-seb** [comment]
Hello @sulabh-msft 

Not reviewing you PR, just had a quick look.

Please update you IDE configuration to match the standard code formatting for SonarQube: https://github.com/SonarSource/sonar-developer-toolset#code-style

**Comment by sulabh-msft** [comment]
@sns-seb , I'm using recommended configurations for IntelliJ

**Comment by sulabh-msft** [comment]
@simonbrandhof ,
 In all my pull requests for sonarqube repo, Integration tests in "Plugins" tests are failing due to missing or bad plugin license for a plugin ("com.A.vb.XYZ.A.A.A").. Is it a known issue?

**Comment by simonbrandhof** [comment]
Hi, the category "plugins" of integration tests require licenses of our commercial products. For this reason it is disabled when executing contributed pull requests. Unfortunately there was a bug in the travis script.  Tests were enabled and so failed because of missing licenses. It should be fixed now in master.

**Comment by sns-seb** [comment]
@sulabh-msft changes in all java files of this PR are using a 4 spaces indentation. 2 space indentation must be used on SonarQube.

**Comment by sulabh-msft** [comment]
Thanks! @sns-seb , I updated all the java files using the "Eclipse Code Formatter"

**Comment by simonbrandhof** [comment]
PR applied. Thanks for the contribution.

**Pull request closed without merging**
